namespace: cavea-back
resources:
  limits:
    memory: "512Mi"  # Maximum memory allowed
    cpu: "600m"       # Maximum CPU allowed (200 milliCPU)
  requests:
    memory: "256Mi"  # Initial memory request
    cpu: "200m"       # Initial CPU request
db_name: cavea_db
mysql_root_password: ""