namespace: cavea-back-prod

image:
  tag: "latest"

resources: 
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "250m"

db_name: cavea_prod_db
db_password: "CHANGE_ME"

app_env: production
app_debug: "false"
app_url: "https://137.74.44.42"

service:
  type: ClusterIP

ingress:
  enabled: true
  tls: true
  tlsSecretName: cavea-back-prod-tls
  path: /
  pathRewrite: false

replicas: 2