namespace: cavea-back-prod

image:
  tag: "latest"

resources: 
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "250m"

db_name: cavea_prod_db
db_password: "CHANGE_ME"

app_env: production
app_debug: "false"
app_url: "https://137.74.44.42"
app_key: "base64:CHANGEME_PROD_KEY"

service:
  type: ClusterIP

ingress:
  enabled: true
  tls: false
  # tlsSecretName: cavea-back-prod-tls
  path: /

replicas: 2