apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{.Release.Namespace}}
  labels:
      {{- include "backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ include "backend.app" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80