name: Laravel Docker Package

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
    outputs:
      image-tag:
        value: ${{ jobs.backend-build.outputs.image-tag }}

jobs:
  backend-build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.build.outputs.image_tag }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine image tag
        id: build
        run: |
          IMAGE_TAG="${{ inputs.version || github.sha }}"
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./cavea-back
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cavea-back:${{ steps.build.outputs.image_tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/cavea-back:latest