name: Backend and frontend CI/CD

on:
  push:
    branches: [ main, dev, feature/** ]
  pull_request:
    branches: [ main, dev ]

permissions:
  contents: write

jobs:
  lint:
    uses: ./.github/workflows/_backend-lint.yml
    secrets: inherit

  tests:
    needs: lint
    uses: ./.github/workflows/_backend-tests.yml
    secrets: inherit

  sonarqube:
    needs: tests
    uses: ./.github/workflows/_repo-sonarqube.yml
    secrets: inherit

  versioning:
    needs: sonarqube
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/_versioning.yml
    secrets: inherit

  backend-build-dev:
    needs: sonarqube
    if: github.ref == 'refs/heads/dev' || github.base_ref == 'dev'
    uses: ./.github/workflows/_backend-build.yml
    with:
      version: ${{ github.sha }}
    secrets: inherit

  backend-build-prod:
    needs: versioning
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/_backend-build.yml
    with:
      version: ${{ needs.versioning.outputs.new-version }}
    secrets: inherit

  backend-deploy-dev:
    needs: backend-build-dev
    if: github.ref == 'refs/heads/dev' || github.base_ref == 'dev'
    uses: ./.github/workflows/_backend-deploy.yml
    with:
      environment: dev
      image_tag: ${{ github.sha }}
    secrets: inherit

  backend-deploy-prod:
    needs: backend-build-prod
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/_backend-deploy.yml
    with:
      environment: prod
      image_tag: ${{ needs.backend-build-prod.outputs.image_tag || needs.versioning.outputs.new-version }}
    secrets: inherit
  
  frontend-build:
    needs: sonarqube
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' || github.ref == 'refs/heads/dev' && github.event_name == 'push'
    uses: ./.github/workflows/_frontend-build.yml
    with:
      profile: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
    secrets: inherit
